version: "3.7"

services:
  app:
    image: nginx_ssh_mysql_php74
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SSH_USERNAME: localheartz
        SSH_PASSWORD: l0c4lh34rtz
        MYSQL_ROOT_PASSWORD: 1nd0n3s14
    container_name: nginx_ssh_mysql_php74
    ports:
      - "7767:22"
      - "7768:80"
      - "7769:3306"
    restart: always
